import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import useMediaQuery from "@/hooks/useMediaQuery";
import ActionButton from "@/shared/ActionButton";
import { SelectedPage } from "@/shared/types";
import AnchorLink from "react-anchor-link-smooth-scroll";
import { motion } from "framer-motion";
import RhettSoccer from "@/assets/RhettSoccer.png";
import KateTennis from "@/assets/KateTennis.png";
const Home = ({ setSelectedPage }) => {
    const isAboveMediumScreen = useMediaQuery("(min-width:1060px)");
    return (_jsx("section", { id: "home", className: "relative bg-gray-20 py-10 md:h-full md:pb-0 overflow-hidden", children: _jsxs(motion.div, { className: "relative mx-auto w-11/12 md:flex md:h-5/6 md:items-center", onViewportEnter: () => setSelectedPage(SelectedPage.Home), children: [_jsxs("div", { className: "z-10 md:basis-2/5 flex flex-col items-center justify-center text-center", children: [_jsxs(motion.div, { initial: "hidden", whileInView: "visible", viewport: { once: true, amount: 0.5 }, transition: { duration: 2 }, variants: {
                                hidden: { opacity: 0, x: -50 },
                                visible: { opacity: 1, x: 0 },
                            }, children: [_jsxs("h1", { className: "text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold text-white leading-relaxed mb-4 md:mb-6", children: ["Welcome to", _jsx("br", {}), "Rhett's Fitness", _jsx("br", {}), "Community"] }), _jsx("p", { className: "text-xl sm:text-2xl md:text-3xl text-white font-medium", children: "Log your workouts every day!" })] }), _jsxs(motion.div, { className: "mt-6 md:mt-8 flex items-center gap-6 md:gap-8", initial: "hidden", whileInView: "visible", viewport: { once: true, amount: 0.5 }, transition: { delay: 0.1, duration: 2 }, variants: {
                                hidden: { opacity: 0, x: -50 },
                                visible: { opacity: 1, x: 0 },
                            }, children: [_jsx(ActionButton, { setSelectedPage: setSelectedPage, children: "Join Now" }), _jsx(AnchorLink, { className: "text-base md:text-lg font-bold text-primary-500 underline hover:text-primary-300 transition", onClick: () => setSelectedPage(SelectedPage.ContactUs), href: `#${SelectedPage.ContactUs}`, children: _jsx("p", { children: "Learn More" }) })] })] }), isAboveMediumScreen && (_jsxs("div", { className: "\n              absolute right-0 top-1/2\n              flex items-center justify-center\n              -translate-y-1/2\n              w-3/5\n              pr-12\n            ", children: [_jsx(motion.img, { src: KateTennis, alt: "Kate playing tennis", className: "absolute z-10", style: { objectFit: "contain" }, initial: { opacity: 0, x: -140, y: 120, scale: 0.78 }, whileInView: { opacity: 1, x: -90, y: 0, scale: 0.78 }, viewport: { once: true }, transition: { duration: 1.4, ease: "easeOut" } }), _jsx(motion.img, { src: RhettSoccer, alt: "Rhett playing soccer", className: "absolute z-20", style: { objectFit: "contain" }, initial: { opacity: 0, x: 140, y: 140, scale: 1.15 }, whileInView: { opacity: 1, x: 90, y: 0, scale: 1.15 }, viewport: { once: true }, transition: { duration: 1.4, ease: "easeOut", delay: 0.1 } })] })), !isAboveMediumScreen && (_jsxs("div", { className: "relative flex justify-center items-end mt-8 h-52 w-full", children: [_jsx(motion.img, { src: KateTennis, alt: "Kate playing tennis", className: "z-10 h-40 w-auto object-contain", initial: { opacity: 0, y: 40 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 1.2, ease: "easeOut" } }), _jsx(motion.img, { src: RhettSoccer, alt: "Rhett playing soccer", className: "z-20 h-48 w-auto object-contain", initial: { opacity: 0, y: 40 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 1.2, ease: "easeOut", delay: 0.1 } })] }))] }) }));
};
export default Home;
